name: Build Simple Android APK (Java Only)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Use simple build configuration
      run: |
        cp build_simple.gradle build.gradle
        echo "Using simple Java-only build"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK (Simple Version)
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload Simple APK
      uses: actions/upload-artifact@v3
      with:
        name: toopan2d-simple-debug
        path: build/outputs/apk/debug/*.apk

    - name: List generated files
      run: |
        echo "Generated APK files:"
        find build/outputs/apk/ -name "*.apk" -type f